### ISSUE TITLE
Sometimes subtotal has empty value and Total price become huge amounts

### ISSUE THREAD

**Issue by BlackStone8960** [miyabitanimchi/ciccc-react-midterm-team-project#10]
![image](https://user-images.githubusercontent.com/60183777/120746544-66e52380-c53a-11eb-9cfb-25f8f7f700f4.png)

**Comment by BlackStone8960** [comment]
Cause: When user adds products to cart without changing quantity, subtotal value has stayed the same as default value ("").
Solution: Set default subtotal value when Detail component gets products information.

**Comment by miyabitanimchi** [comment]
I'm sorry I didn't notice that. I really appreciate that you figured out that cause.

**Comment by BlackStone8960** [comment]
Don't be sorry! It happens.
